FROM maven:3.6-ibmjava-8 as compile
LABEL maintainer="IBM Java Engineering at IBM Cloud"

# Ensure up to date / patched OS
RUN  apt-get -qq update \
  && apt-get -qq install -y curl wget xmlstarlet unzip \
  && DEBIAN_FRONTEND=noninteractive apt-get -qq upgrade -y \
  && apt-get -qq clean \
  && rm -rf /tmp/* /var/lib/apt/lists/* \
  && mkdir -p /mvn/repository

#setup project folder for java build step
COPY . /project
COPY ./mvn-stack-settings.xml /usr/share/maven/conf/settings.xml

# OSGI core for version range processing
RUN  /project/util/check_version build

WORKDIR /project/user-app

RUN /project/java-spring-boot2-build.sh package

####
FROM adoptopenjdk:8-jdk-openj9

ARG artifactId=appsody-spring
ARG version=1.0-SNAPSHOT
ENV JVM_ARGS=""

LABEL maintainer="IBM Java Engineering at IBM Cloud"
LABEL org.opencontainers.image.version=${version}
LABEL org.opencontainers.image.title=${artifactId}

COPY --from=compile /project/user-app/target/app.jar /app.jar

RUN apt-get update \
  && apt-get install -y --no-install-recommends curl wget criu iptables \
  && apt-get clean \
  && rm -rf /tmp/* /var/lib/apt/lists/* \
  && wget https://raw.githubusercontent.com/bharathappali/appsody-criu/master/criu-controller.sh \
  && chmod +x criu-controller.sh


EXPOSE 8080

WORKDIR /

ENTRYPOINT [ "sh", "-c", "/criu-controller.sh" ]

